package co.edu.uniquindio.taller2.tests;

import org.junit.Assert;
import org.junit.Test;

import co.edu.uniquindio.taller2.model.Banco;
import co.edu.uniquindio.taller2.model.CuentaException;

public class TestBankFalse {
	@Test
	public void test() {
		Banco bank = new Banco("Bancolombia", "Cra 9 # 23 - 01", "AB-001");
		try {
			bank.agregarCuentaAhorros("A001", 0, 0);
		} catch (CuentaException e) {
			Assert.fail(e.getMessage());
		}
		try {
			bank.agregarCuentaAhorros("A001", 0, 0);
		} catch (CuentaException e) {
			Assert.fail(e.getMessage());
		}
	}

	@Test
	public void TestBancoAgregarCuenta2() throws CuentaException {

		Banco bank = new Banco("Bancolombia", "Cra 9 # 23 - 01", "AB-001");
		// Agrega una cuenta de ahorros
		bank.agregarCuentaAhorros("A001", 0, 0);
		// Agrega una cuenta de ahorros cnon el mismo código (error)
		bank.agregarCuentaAhorros("A001", 0, 0);
	}
}
